"""hobby

Revision ID: cf77efd8732f
Revises: 68f0c3538171
Create Date: 2019-06-22 23:12:25.171788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf77efd8732f'
down_revision = '68f0c3538171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hobby',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hobby', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hobby')
    # ### end Alembic commands ###
